# Generated by Django 5.2.17 on 2026-09-09 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('type_piece', models.CharField(max_length=50)),
                ('numero_piece', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('observation', models.TextField(blank=True)),
                ('date_heure_entree', models.DateTimeField()),
                ('date_heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('SORTI', 'Sorti')], default='PRESENT', max_length=10)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites', to='gestion_visites.service')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites', to='gestion_visites.visiteur')),
            ],
        ),
    ]
