# Generated by Django 5.2.17 on 2026-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_visites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteur',
            name='date_delivrance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='document_cnib',
            field=models.FileField(blank=True, null=True, upload_to='documents_cnib/'),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='structure_delivrance',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
